Test AdmArea._get_country_data
pkollenda/PISA_fork pull request #6
Opened 2024-11-16 20:06 UTC by operte

I created two tests for `AdmArea._get_country_data`. This method is called in the `__init__` so I didn't explicitly call it in the tests.

I created two GeoDataFrame fixtures which I think will be useful for other tests, since we use the geometry of the administrative areas for other methods.

I am mocking the output of `GADMDownloader.get_shape_data_by_country_name` but I am not sure if this avoids calling it or not, because when I added a breakpoint to the method, I could see the output expected as if the code was running as normal 🤔

2024-11-16 20:09 UTC, operte commented on tests/test_layers.py
> +                break
The idea here is to read the stderr output line by line, search for the line that comes before the content I want to test, and then have the actual `assert`. After that I don't need to continue reading more lines, so I just `break` the loop.

2024-11-16 20:10 UTC, operte commented on tests/test_layers.py
> +        printed_output = capsys.readouterr().out.strip().split('\n')
`capsys` is a `pytest` fixture to capture the stderr. I didn't know about it. I assume we'll get rid of this once we change the `print`s to logging.

2024-11-23 17:07 UTC, operte reviewed
The "issue" I was seeing with the mocking not working seems gone. The behaviour now is as expected. Even before updating the method path from `gadm.*` to `layers.*`. It might have been something weird with my local setup 🤷

2024-11-23 17:07 UTC, operte commented on pyproject.toml
> +pytest-mock = "^3.14.0"
@dcossao I changed the order of the import

2024-11-23 17:07 UTC, operte commented on tests/test_layers.py
> +    return MultiPolygon([polygon1, polygon2])
@dcossao I refactored the fixtures so there's only one now, which is more useful than before.

2024-11-23 17:07 UTC, operte commented on tests/test_layers.py
> +        assert adm_area.geometry == multipolygon
@dcossao I added this check, as you suggested.

2024-11-25 14:48 UTC, dcossao requested changes

2024-11-25 14:48 UTC, dcossao commented on pyproject.toml
I think it might be better to have pytest-mock in the `dev dependencies` group

2024-11-25 14:48 UTC, dcossao commented on pyproject.toml
> +pytest-mock = "^3.14.0"
I ran poetry install and it’s complaining: 

`pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.`

That should work. In the future, I think it’s a good idea to install dependencies that belong in this group as in this example:

`poetry add -G dev pytest-mock`

2024-11-25 15:43 UTC, operte commented on pyproject.toml
Done!

2024-11-26 17:22 UTC, operte commented on pyproject.toml
> +pytest-mock = "^3.14.0"
You are right, I didn't install it with that command. Thanks for the tip! 

The lockfile should now be up-to-date!

2024-11-28 09:03 UTC, dcossao approved these changes

2024-11-28 09:04 UTC, merged